const unitNames = ["qp", "suguri", "marc", "kai", "yuki", "hime", "fernet", "poppo", "poppo", "aru", "sora", "peat", 
"tomomo", "tomomo", "chicken", "ball", "seagull", "master", "brobo", "castle", "chicken", 
"ball", "seagull", "master", "brobo", "castle", "bpoppo", "hw2019pumpkin", "syura", "nanako", "qpd", 
"saki", "ksuke", "krila", "kae", "alte", "kyoko", "npoppo", "sham", "sherry", "sorasp", "starb", "sweetb", 
"arus", "nath", "mimyuu", "tomato", "kiriko", "non", "ceor", "miusaki", "yukid", "tmsw", "sugurib", "tsih", 
"tequila", "mei", "natsumi", "nico", "arthur", "iru", "mira", "cuties", "cuties", "yuuki", "islay", "mio", 
"suguri46", "sumika", "ellie", "lulu", "marcpilot", "alicianrone", "teotoratta", "non_head", "tmsw", "teq_minion",
 "yuuki", "mio", "blob", "troll", "lizardit", "mpoppo", "heliseed", "doll", "golem", "teq_minion",
"arnelle","maynie","chris","kyupita"];

const eventMusicNames = [
  "main_menu",
  "standby",
  "dialog1",
  "dialog2",
  "dialog3",
  "conclusion",
  "ending1",
  "dialog4",
  "final2",
  "ending2",
  "idol_duet",
  "idol_instrumental",
  "idol_poppo",
  "dialog5",
  "dialog6",
  "ending3",
  "tomomo_sweeteater",
];